### ISSUE TITLE
full-qualified class resolving not recognized

### ISSUE THREAD

**Issue by Stefku** [anthraxx/intellij-awesome-console#1]
Hi there. In the screenshot is shown that one can click on a class source like Foo.java.
Did you thought about the possibility to make a class in format com.example.Foo also clickable?

**Comment by anthraxx** [comment]
Good idea, we will have a look at this for a following version.

**Comment by anthraxx** [comment]
This enhancement was implemented with commit 49ac7b2c32d4005808f14459935c670fa999d8de and e8a4231fea51d6c293ae243b3082a240a6bcdc92.
We released an updated version 0.1337.2, you should get it through the regular IntelliJ plugin update.

**Comment by Stefku** [comment]
Thanks!

How does this new feature work? I have text like following in the run console, but the classes are not clickable.

```
2015-02-06 11:58:01,402 [DEBUG|ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung|TracingInvocationHandler]       \\  -> ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung
2015-02-06 11:58:01,402 [DEBUG|ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung|TracingInvocationHandler]       \\  -> ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung
2015-02-06 11:58:01,402 [DEBUG|ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung|TracingInvocationHandler]       // <-  ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung
2015-02-06 11:58:01,402 [DEBUG|ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung|TracingInvocationHandler]       // <-  ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService.validiereVerbindung
2
```

**Comment by anthraxx** [comment]
you have the method name inside the logging right after the classname without any whitespace seperator.
we do not parse arbitrary sub-parts of the fully qualified class name as this would lead to multiple possibilities (especially with different languages).
you should add a space (and or other delimiter) after the classname 'FahrplanService' separating the method name 'validiereVerbindung'. For example: "ch.sbb.mct.vermittler.reise.business.fahrplan.FahrplanService -> validiereVerbindung"

if you are using a log4j pattern, you can also add the line-number behind the class-name seperated with a colon (like FahrplanService:42).
example pattern: "%d{HH:mm:ss} %-5p [%t] (%c{1}.java:%L) %M -> %m%n"

PS: it looks a little bit noisy with all the fully qualified things in your log line

**Comment by anthraxx** [comment]
PPS: if you want TracingInvocationHandler to be clickable you can add the filetype suffix like "TracingInvocationHandler.java"
Using Basename only without filetype every single word in each line has to be parsed and resolved (remind that this also works for non-Java languages). Even with caching this will be high overhead if you are running a big multi threaded environment like message queues with high amount of workers and log level debug (or even trace).

Hope you can consider changing the logging output slightly in one or the other way

**Comment by Stefku** [comment]
Thank you for your detailed response. I see what you mean.

**Comment by kurtseebauer** [comment]
is it right that fully qualified classes are not supported? like
my.namespace.Myclass.java:25
?

**Comment by anthraxx** [comment]
@kurtseebauer they are

**Comment by kurtseebauer** [comment]
they don't work for me. Other  files work, like:
logback.xml
or the notation in stack traces:
at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:406)
in IntelliJ 2016.3. 
First I suspected that the grep console plugin interfered with awesome console, but after uninstalling that it didn't change anything. 
Any ideas?

**Comment by anthraxx** [comment]
@kurtseebauer please retry once 0.1337.6 appears in the plugin repos and report back if it works or doesn't. Right now its pending but already uploaded to their servers.

**Comment by kurtseebauer** [comment]
Will do, thank you!

**Comment by kurtseebauer** [comment]
still not working. sample:
14:06:35.245  INFO  com.opensymphony.xwork2.util.logging.commons.CommonsLogger.java:46 - Choosing bean (struts) for (com.opensymphony.xwork2.ObjectFactory)

**Comment by anthraxx** [comment]
@kurtseebauer and that is directly a source inside your project? all our test cases work,, i don't see why it shouldn't

**Comment by kurtseebauer** [comment]
the sample was bad indeed, because it's not one of my own files. the problem however remains. I made a very simple program to demonstrate it:

package com.company;

public class Main {

    public static void main(String[] args) {
        System.out.println("com.company.Main.java:5"); // does not work
        System.out.println("com.company. Main.java:5"); // works because of the space before "Main"
    }
}

Tested with plugin version 0.1337.6, idea version #IU-163.7743.44 (16.3.3) and #IU-171.2455.10 (2017.1 EAP).

**Comment by anthraxx** [comment]
@kurtseebauer We sent some elves to look into this issue, they actually found out the cause:
Your logger produces an output wich is a mixture of fully qualified filenames (containing an extension and path seperators) and a fully qualified class-name (containing the package and the class name).

While theoretically its the output that produces strange artifacts to look up, we though about this and integrated a detection for this mixed output mode in 460badbd2d6073e10507f944b8ef1cf7c6109f1f.
You could either test the master from source, or wait a bit until we release this fix later this week.
