### ISSUE TITLE
Not working in idea 14.1

### ISSUE THREAD

**Issue by naixia** [anthraxx/intellij-awesome-console#11]
Seems just not working after I installed the plugin. Nothing new inside the "terminal" tab console.
Do I need to configure/turn-on anyting/settings?

**Comment by anthraxx** [comment]
@naixia are you maybe mixing up the terminal and the console? :smile:
As the screenshot states, this is a plugin which extends the console, the tab that outputs logs about the running process started in IntelliJ. Its not the terminal tab which executes shell commands

**Comment by naixia** [comment]
Thanks for reply. Yes, I think I mixed them up. But I really want to have your plugin work also in the terminal tab -- e.g. When I build/compile files in terminal, it would be very nice if the output errors can be clicked. Well, its actually a feature request ;)

**Comment by tsegbert** [comment]
Thank you for your suggestion!
But unfortunately the Terminal is out of scope of this plugin.
