### ISSUE TITLE
file not detected when using (non root relative) subdirectory without leading slash

### ISSUE THREAD

**Issue by mgerhardy** [anthraxx/intellij-awesome-console#13]
the file is not detected: as you can see the file is part of the project
![bildschirmfoto von 2015-06-23 13 57 19](https://cloud.githubusercontent.com/assets/577713/8305469/c1baf7f4-19af-11e5-861d-fe08180e3b2b.png)

... but it is not highlighted.
![bildschirmfoto von 2015-06-23 13 56 27](https://cloud.githubusercontent.com/assets/577713/8305462/ad41acd2-19af-11e5-9b71-ea9af9a60946.png)

**Comment by anthraxx** [comment]
we believe this issue is fixed in the 0.1337.6 release, which should appear soon in the plugin repositories (plugin already uploaded).
If you still encounter issues, please notify us about it.
