### ISSUE TITLE
not working in Terminal tab

### ISSUE THREAD

**Issue by oppianmatt** [anthraxx/intellij-awesome-console#14]
![tasks_main_yml_-_pitchup_com_-____source_pitchup_com_](https://cloud.githubusercontent.com/assets/48596/8851450/6bc23a56-3147-11e5-9f2e-c17c7882f2db.png)

How do you enable this?

**Comment by tsegbert** [comment]
The Terminal tab is not supported by this plugin. It highlights links in the console, not in the terminal.

**Comment by oppianmatt** [comment]
Can we get it to work on the terminal tab then please? Would make ansible editing a whole lot easier (and anyone else that runs terminal apps in pycharm/intellij that use files in the editor).

**Comment by reesd** [comment]
+1 for terminal support. It would be very handy for lots of bash driven testing commands that output file links. Does Terminal provide the hooks to do it?
