### ISSUE TITLE
file paths starting with dot are not recognized

### ISSUE THREAD

**Issue by ssbarnea** [anthraxx/intellij-awesome-console#18]
It seems that the plugin does not recognize file paths starting with dot (relative to project root).

```
/usr/local/bin/flake8
./wstools/TimeoutSocket.py:52:13: F821 undefined name 'apply'
./wstools/TimeoutSocket.py:69:21: F821 undefined name 'apply'
```

<img width="643" alt="screenshot 2016-07-23 16 03 33" src="https://cloud.githubusercontent.com/assets/102495/17078595/1f784f32-50ef-11e6-93ca-c32b8e2d5cb4.png">

**Comment by anthraxx** [comment]
we believe this issue is fixed in the 0.1337.6 release, which should appear soon in the plugin repositories (plugin already uploaded).
If you still encounter issues, please notify us about it.
