### ISSUE TITLE
Doesn't work in Rubymine 2016.2.5

### ISSUE THREAD

**Issue by greena13** [anthraxx/intellij-awesome-console#19]
Installed and none of the paths in the terminal are clickable when running a node process.

I tried disabling all other terminal related plugins, but it still doesn't work.

OSX El Capitan 10.11.6
Java 8 Update 111
Rubymine 2016.2.5

Terminal-related plugins:

Awesome Console 0.1337.5
BashSupport 1.5.8.162
Grep Console 6.3.141.000
Terminal 0.1

I've also notice that the release notes for version 1.1337.4 mention adding settings to Settings > Other Settings, however there is no entry for Awesome Console in my settings dialog, under Other Settings. 

Awesome Console appears in the omnisearch box when searching "awesome" and is listed as enabled.

It _does_ work if I pipe the output of the same node process to a file and tail that file. An ok work around for now, but my understanding was that Awesome Console worked with all output to the terminal window in Rubymine. Am I mistaken?

**Comment by anthraxx** [comment]
no, the console and the terminal are two different things... its a plugin that integrates into the log output of your console when running inside the IDE (not the terminal emulator that gives you a shell)

**Comment by anthraxx** [comment]
no response from reporter
