### ISSUE TITLE
abs paths should open project files in pycharm

### ISSUE THREAD

**Issue by avshyz** [anthraxx/intellij-awesome-console#20]
Python tracebacks throws this one off the track. 
When I try to click on a file path (looks something like 'File /Path/To/Erroneous/File.py, line x...') instead of opening the file in pycharm, it opens that in my external editor (atom). 
Can you, before opening externally, check if the clicked file link is in the project directory? 
that would make this plugin truly shine.

Thanks a lot!

**Comment by dawez** [comment]
Also happening in IntelliJ with python files

**Comment by anthraxx** [comment]
not really as it just uses the file opening mechanics of the intellij plugin mechanics and therefor uses your systems associated mime type for that file type (being .py).
You should switch your default editor for that mime type to intellij instead.
