### ISSUE TITLE
File path not linkified

### ISSUE THREAD

**Issue by humblehacker** [anthraxx/intellij-awesome-console#22]
Any idea why this path isn't linkified:

    /Users/david/Library/Developer/CoreSimulator/Devices/7BD29374-43E5-40FE-BCA5-B1390C0559EE/data/Containers/Data/Application/9D25D0E1-3CAF-417B-A468-56815D016409/Library/Application Support/database.db

While this one (and every other one, in fact) is?

    /Users/david/Library/Developer/CoreSimulator/Devices/7BD29374-43E5-40FE-BCA5-B1390C0559EE/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles

I thought maybe it had to do with the space in `Application Support`, so I tried alternately replacing it with a backslash escaped space, replacing it with `%20`, and quoting the entire path, with no luck.

**Comment by anthraxx** [comment]
because there is a space in the directory, recognition is not taking spaces into account (yet) as that can be extremely resource consuming. Maybe in a future version with a confuguration option

**Comment by frankmayer** [comment]
I stumbled upon the same thing, too. Had totally forgotten, that I had installed your plugin and reported this to JetBrains.
Here's the ticket (and my screenshot) that I opened (and now closed) at Jetbrains: https://youtrack.jetbrains.com/issue/WI-35097

**Comment by anthraxx** [comment]
duplicate or better named #29
