### ISSUE TITLE
Add support for Terminal as well

### ISSUE THREAD

**Issue by reesd** [anthraxx/intellij-awesome-console#23]
FYI, I filed https://intellij-support.jetbrains.com/hc/en-us/requests/856571 asking for IntelliJ to add hooks to Terminal for filtering and linking.

**Comment by Kisty** [comment]
The link is broken. Can you give a working URL or post on [the issue tracker](https://youtrack.jetbrains.com/issues/IDEA) instead?

**Comment by anthraxx** [comment]
@reesd is there any update? Can you provide a working link so we can track this?

**Comment by anthraxx** [comment]
an update has been released with fast terminal support and should arrive in the marketplace.

PS: I would be incredibly happy to get some ratings in the jetbrains marketplace. Lately it seems nobody gives any rating except if after happily using the plugin for years free of charge and in latest intellij 2020.2 update a performance regression with the terminal arrives, then instant going to the rating and giving 1 star, which is super demotivating for a free project :crying_cat_face:

**Comment by Kisty** [comment]
Thanks! 

That sucks about the reviews, dude. Happy to help out. Here's the link if there's anyone else who wants to review. Might I suggest putting it in the GH project's description at the top? Had to search for it:
https://plugins.jetbrains.com/plugin/7677-awesome-console

**Comment by studgeek** [comment]
Sorry for me not responding on the broken link sooner.
Just tried out the Terminal support, its super handy. I put a review up also!

**Comment by anthraxx** [comment]
Thank you very much, this makes me really happy 😊
I try to extend the functionality soon to support other weird edge cases 🙂
