### ISSUE TITLE
file:/// path not linkified

### ISSUE THREAD

**Issue by Kisty** [anthraxx/intellij-awesome-console#25]
Love the concept of this plugin but I'm an Android developer and executing tests gives failures giving URIs prefixed with `file:///` and so aren't linkified. Would this be easy to add support for? If so, I could have a crack at adding it.

**Comment by Kisty** [comment]
Hmm, it looks like that the plugin already supports this, but my link `file:///home/tim/Documents/source/learn2/app/build/reports/androidTests/connected/flavors/CAM/index.html` isn't linkified. I've restarted Android Studio (IntelliJ-based IDE) as prompted. Any idea why this isn't working? There are no spaces present.

**Comment by Kisty** [comment]
Upon running filter and integration tests, adding the path, the link get's filtered fine, but the integration test fails :(. Using IntelliJ 2017.2, OpenJDK 1.8.0_131 on Ubuntu 16.04 LTS.
![screenshot from 2017-07-18 10-17-59-console](https://user-images.githubusercontent.com/3243752/28310091-39298f48-6ba3-11e7-972e-f4c0851583b3.png)

**Comment by Kisty** [comment]
Ah, this is because the terminal isn't supported. Doh! Related to #23

**Comment by anthraxx** [comment]
So this is not an issue per se as the logs are contents of the terminal rather then the log output? If so, it is indeed #23 and you could close this separated issue?

**Comment by Kisty** [comment]
Aye, you're right @anthraxx. Closing.
