### ISSUE TITLE
Config page not visible

### ISSUE THREAD

**Issue by holycrepe** [anthraxx/intellij-awesome-console#28]
The configuration page is no longer visible. Fixed by PR #26

**Comment by jamesdwilson** [comment]
This affects me too

**Comment by anthraxx** [comment]
going to pull this in soonish

**Comment by Casebash** [comment]
I have this trouble as well. In fact, I installed it and it seems to do nothing WebStorm 2017.2.4

**Comment by anthraxx** [comment]
fixed in master, thanks
