### ISSUE TITLE
Comma und closed Bracket recognized as file path

### ISSUE THREAD

**Issue by iice** [anthraxx/intellij-awesome-console#30]
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: de.my.web.common:my-common-sms:jar -> duplicate declaration of version ${my.version} @ de.my.web.anwendungen:parent:0.1-SNAPSHOT, **C:\tmp\web\projekte\anwendungen\pom.xml,** line 221, column 25

The project de.my.web.anwendungen:my-anwendung-unfall-bl:0.1-SNAPSHOT (**C:\tmp\web\projekte\anwendungen\my-anwendungen\my-anwendung-unfall-bl\pom.xml)** has 1 error

**Comment by anthraxx** [comment]
well technically both, comma and brackets are valid characters for files, not sure what to do about this

**Comment by iice** [comment]
Is it possible to configure the regex for the last character of file path without comma and bracket?

**Comment by anthraxx** [comment]
Not right now, but something like that could be possible. Let me think a bit how to approach it and if it would make sense to add default cases to handle this. After all, ending files with such characters is unlikely

**Comment by anthraxx** [comment]
this should be fixed in the master and released soon via plugin update.
If this issue persists, please request reopen and we analyze it further
