### ISSUE TITLE
Functionnal regression in standard stacktrace output

### ISSUE THREAD

**Issue by nicknolt** [anthraxx/intellij-awesome-console#32]
When an exception occured, the stacktrace is writen in the intellij console especially a link to the file where the error come, but this link dont work anymore with awesome console.

Under windows, a cmd windows pop up then disapear and nothing happend.

By example :
--------------
Error
Traceback (most recent call last):
  File "C:\Users\{UserName}\{path}\test_combo_box.py", line 191, in test_binding_command_with_combo
--------------

"C:\Users\{UserName}\{path}\test_combo_box.py" is a link in the standard console and the functionnal behavior (redirect in Intellij in the right file) dont work anymore.

**Comment by Kisty** [comment]
If this is the same problem with trying to open a full path on Windows:

In the console: `C:\Users\Me\path\to\file.txt:60:`

> Windows cannot find file `file:///C:\Users\Me\path\to\file.txt:60:` 
> Make sure you've entered in the right path and try again

**Comment by anthraxx** [comment]
This should be fixed in master and available in the next update (which is scheduled next week)
If this problem persists please leave a message for further investigation.
