### ISSUE TITLE
Ability to open files generated by ts-loader (webpack)

### ISSUE THREAD

**Issue by davidm-public** [anthraxx/intellij-awesome-console#33]
The output of ts-loader run from webpack is as follows:

``` error  in /Users/... path shortened ... /FileA.ts(182,31) ```

am wondering if it would be possible to parse that line and navigate to the relevant source file and line?

See screenshot attached to this issue:
https://youtrack.jetbrains.com/issue/WEB-29833

**Comment by anthraxx** [comment]
fixed in master and will be available with the next update.
If it still persists once the update is rolled out, please notify for further investigation
