### ISSUE TITLE
Support absolute paths with line numbers 

### ISSUE THREAD

**Issue by grzegorz-wolszczak** [anthraxx/intellij-awesome-console#34]
There are tools (e.g. java checkstyle plugin, cpp compiler, etc. ) that produce stack traces/logs with file paths with line numbers
e.g.

`C:\\some_dir\\some_file:4:` (with additional colon at the end)

Currently awesome console does recognize this , but not as file path but rather as  url and tries to open this path with web browser after clicking on the link.

I believe this could be easily recognized as file path and awesome console should open the file and actually position the cursor on the line number.

**Comment by anthraxx** [comment]
this should be fixed in the master and released soon via plugin update.
If this issue persists, please request reopen and we analyze it further
