### ISSUE TITLE
paths are ignored - only filename is used to link to file

### ISSUE THREAD

**Issue by mark-anders** [anthraxx/intellij-awesome-console#36]
It seems like the path name of a file - even if fully qualified - is ignored when determine the file to link to. So, for example, clicking on the following link:

     cs/src/app/__init__.py:83

Would bring up a list of every __init__.py function, which is a huge list - maybe 1000 or more!  If you don't know python, __init__ is an object's constructor.  What's worse, the one I'm looking for is at the bottom of the list, as installed libraries come first.

It's good to allow ambiguous names, but if qualified, it should filter the list and hopefully go directly there.

**Comment by mjarmstr** [comment]
I'm seeing something similar, but not exactly the same.  I have a path like this.
```
verifier\framework.py:12:1: 
```
And what gets linkified is `\framework.py:12:1:` so when I click on it I get and error that Windows cannot find `file:///c:\framework.py:12:1:`

**Comment by anthraxx** [comment]
fixed in master, release will be deployed soon
