### ISSUE TITLE
Clicking on a link attempts to open it with standard editor instead of inside phpStorm

### ISSUE THREAD

**Issue by bits-of-static** [anthraxx/intellij-awesome-console#38]
Which does not even work, because of the trailing line number.
E.g. ` E:\Codebase\tool-copyHelper\src\Location\Location.php:73`.

The directory `...\src` is marked as sources root.

Windows10, PhpStorm 2017.3.6

**Comment by Rublis** [comment]
for this to work You'll need two fixes: #42 and #43

**Comment by Rublis** [comment]
For Your case #42 should be enough. Till it's merged, You can try to check by installing it manually from: https://github.com/Rublis/intellij-awesome-console/releases/tag/0.1337.7

**Comment by anthraxx** [comment]
this should be fixed in the master and released soon via plugin update.
If this issue persists, please request reopen and we analyze it further

**Comment by EricRabil** [comment]
This issue is still not fixed, at least for WebStorm and PyCharm – not sure about PHPStorm. Could the issue be re-opened?
