### ISSUE TITLE
Paths with string representation of newlines are not linkified

### ISSUE THREAD

**Issue by Minothor** [anthraxx/intellij-awesome-console#39]
Similar to spaces mentioned in #22 paths mentioned in strings don't currently trigger parsing.
e.g.: the `[file:line:column]\n..` etc.. below:
`at /home/njb/WebstormProjects/iab-vpaid/packages/vpaid/test/testabulous/vpaid-validate.spec.js:15219:47\n\nTypeError: (0 , _history.getTagFilters) is not a function`

Would it be possible to let Users define logging patterns perhaps, even if only as a way to cut down on 'bug' reports here?

Either way, aptly named plugin by the way, cheers!

**Comment by anthraxx** [comment]
Honest question, how do you get broken output like that? Isn't that something that should be fixed on your side while logging?

**Comment by anthraxx** [comment]
closed due to no feedback after ~ 2 years
