### ISSUE TITLE
can't support Chinese charater

### ISSUE THREAD

**Issue by zzhzzh204553** [anthraxx/intellij-awesome-console#46]
`Z:\PALO\12_高一\考试\高级中学.docx`

**Comment by anthraxx** [comment]
fixed in master and will be available with the next update.
If it still persists once the update is rolled out, please notify for further investigation

**Comment by iamqiz** [comment]
hello 
it still  not work on chinese char

![image](https://user-images.githubusercontent.com/48077521/154825780-991131b2-c8a4-453a-a0d9-6a8bc422a1ce.png)
pycharm 2020.1.3  
plugin version: 0.1337.9
