### ISSUE TITLE
Regression for eslint output? 

### ISSUE THREAD

**Issue by jasperblues** [anthraxx/intellij-awesome-console#51]
Setting up new laptop. I'm sure this has worked before, however it is not currently: 

```
> @ lint:src /Users/jblues/mobbiz/LOSMobileApp
> eslint . --ext .ts


/Users/jblues/mobbiz/LOSMobileApp/navigation/AppNavigator.ts
  1:8  error  'React' is defined but never used  @typescript-eslint/no-unused-vars

✖ 1 problem (1 error, 0 warnings)
```

Instead of opening editor another app opens. 

Latest Webstorm and plugin version.

**Comment by jasperblues** [comment]
It worked after changing file type associations.

**Comment by gdelmas** [comment]
@jasperblues where did you change the file type associations?

**Comment by jasperblues** [comment]
@gdelmas on a Mac it is `Get Info` on a file, then set the App, then click "Change All" button. 

![image](https://user-images.githubusercontent.com/430321/98309430-5d77f500-2005-11eb-94d6-010f89ab39f0.png)

**Comment by mathieutu** [comment]
This is not actually a proper solution.
I want my mac to open them in vscode which is way liter, but when I am in a webstorm project, links should open in the editor.

**Comment by gdelmas** [comment]
@jasperblues @mathieutu apart from that, it is trickey to select WebStorm in that menu, as the location of the executable changes with each WebStorm update, when it is installed with the JetBrains Toolbox

**Comment by jasperblues** [comment]
@gdelmas I _believe_ if it is found once, OSX will remember, even if the location changes when the next toolbox version comes. 

All, please feel free to reopen the issue in collaboration with the project authors. I closed the issue because I was personally satisfied with the workaround, and did not have time to contribute further.
