### ISSUE TITLE
Add support for windows paths

### ISSUE THREAD

**Issue by bertyhell** [anthraxx/intellij-awesome-console#52]
Could you add support for windows paths containing forward slashes?

example tslint outputs paths like this:
C:/Users/bert/Documents/my-file.const.ts:37:1

If i try to open one of these i get:
![image](https://user-images.githubusercontent.com/1710840/74221777-244b6800-4cb3-11ea-99f0-160c076a3b8d.png)

I'm guessing replacing the forward slashes by backward slashes might fix the issue

**Comment by hoeni** [comment]
Same here, but I suppose the problem is due to the passed colon and line number at the end.
However, it would be a great help to have this fixed...

**Comment by bertyhell** [comment]
@hoeni I created a PR with a fix. Let's hope the maintainer merges it.
https://github.com/anthraxx/intellij-awesome-console/pull/53

**Comment by MaxmaxmaximusGitHub** [comment]
![image](https://user-images.githubusercontent.com/60403187/81035703-cd65c100-8ea4-11ea-9b1e-7efc66fe5a36.png)

**Comment by bertyhell** [comment]
@MaxmaxmaximusGitHub What should i be looking at in your image?
That map files are not mapped correctly?
Is this my pr that you are running?

**Comment by MaxmaxmaximusGitHub** [comment]
@bertyhell  `static\` not part of path, but it is

**Comment by bertyhell** [comment]
@MaxmaxmaximusGitHub i'm not sure if this "static part not being highlighted" is part of this PR, since the regex that i changed does correctly inlcude it

The original regex selected `static\` but didn't select `c:\`

![image](https://user-images.githubusercontent.com/1710840/81606591-a858dd00-93d3-11ea-9864-ba5f957c4960.png)

The regex in my PR does correctly select `static\` and also correctly selects `c:\`

![image](https://user-images.githubusercontent.com/1710840/81606701-d2120400-93d3-11ea-8127-f014b5a171a3.png)


The static issue might be a bug somewhere else in the code, but unrelated to my PR

**Comment by bluelovers** [comment]
![image](https://user-images.githubusercontent.com/167966/94068819-477dee80-fe22-11ea-84db-2dd1a4e33f73.png)

**Comment by anthraxx** [comment]
Some of these cases should be handled by f5177c40566b6ff3821eec7669cf84e9a4ebde72 (no whitespace through) new cases should be opened separately after the next release
