### ISSUE TITLE
Tilde is not a path in Angular output

### ISSUE THREAD

**Issue by miloshavlicek** [anthraxx/intellij-awesome-console#54]
When an error occurs in my Angular (v 9.0.1) app, I see invalid links on tilde characters which are not links, but only highlight of the line above.

See below:
![image](https://user-images.githubusercontent.com/2387790/79320677-79516780-7f0a-11ea-9bf6-e064dfcfb5d3.png)

**Actual bebavior:**
`~~~~`
is transformed as link.

**Expected behavior:**
Tilde characters without links.

**Comment by anthraxx** [comment]
is the directory really named `@app` or is that just a marker?

**Comment by miloshavlicek** [comment]
@anthraxx Yes, it's directory name as is.

**Comment by travigd** [comment]
This is a TypeScript thing, not just Angular. :^)

**Comment by InsOpDe** [comment]
![image](https://user-images.githubusercontent.com/10099328/92639225-c67c0e80-f2db-11ea-9211-f1f5e2b2e0ab.png)
similiar problem with linux home alias `~` or should i open an extra issue for this?
