### ISSUE TITLE
Line number not detected for traceback package line formatting

### ISSUE THREAD

**Issue by eransevi** [anthraxx/intellij-awesome-console#58]
A common package in python is "traceback" and it's used by many core python packages. It has the following format for stack trace lines:

'  File "%s", line %d, in %s' % (filename, lineno, name)

reference: lib-python/2.7/traceback.py:39

For example: `File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/teamcity/diff_tools.py", line 38, in _patched_equals`

However with this format the line number is not recognized properly by the plugin so the file is opened but not at the correct position.

Is it possible to support this formatting as well? 

I'm using PyCharm CE 2020.1.3 and the plugin version of 0.1337.8

**Comment by Alexqwesa** [comment]
I confirm, and also:
by default pycharm would recognize path like this: File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/teamcity/diff_tools.py", line 38,

but this plugin break it

**Comment by anthraxx** [comment]
This has been improved in 91bae3bc7a0e9f4246a08f74d986b7229f37bd91
however there will still be whitespace boundaries which is a problematic portion tracked in https://github.com/anthraxx/intellij-awesome-console/issues/29
So for now only quotes traceback paths without spaces will work.
