### ISSUE TITLE
Terminal blinking in last PyCharm CE version.

### ISSUE THREAD

**Issue by perevertysh** [anthraxx/intellij-awesome-console#59]
In 2020.2 PyCharm CE terminal begins blinking if resized it. Also there is some problem with terminal in runtime: it shows output line by line, but in standard it shows all output lines immediately. 
OS: Ubuntu 18.04

**Comment by anthraxx** [comment]
This plugin has nothing to do with the terminal of intellij, its about the console which has runtime logging output etc.

**Comment by comxd** [comment]
This plugin make my **terminal** (and console) very slow and each commands cause blinking it.

Confirmed using PhPStorm 2020.2 under Linux ((K)Ubuntu 20).

Disabling the plugin "resolve" this issue.

**Comment by anthraxx** [comment]
This issue is related to #56 and will be fixed during the weekend release. Sorry for the delay and the bug, you will be able to enable the plugin again with the next version. In case there is still something open, please be invited to create a new issue.
