### ISSUE TITLE
File:line link in console can go to wrong source line when intellij collapses code lines

### ISSUE THREAD

**Issue by NickCody** [anthraxx/intellij-awesome-console#75]
IntelliJ can collapse parts of the source file and as a result, Awesome console will go to the wrong line for source files that have some collapsed lines. Collapsed lines can be collapsed imports, collapsed function definitions, etc.

Awesome console seems to go to the "literal" editor buffer line number, rather than the true line number which shows in the gutter.

**Comment by anthraxx** [comment]
I don't think the API offers a way to go to the "native" line number unfortunately. All that the API seems to offer is a virtual file with specified line and column, which we add. Unfortunate

**Comment by NickCody** [comment]
Gotcha. I can work around this. Thanks for your speedy response, Levente.

**Comment by jlous** [comment]
Editor.logicalToVisualPosition should be be helpful for calculating the correct line
